[[lines]]
name = "wasted"
text = "WASTED"
female = false
city17 = true
pitch = -11.0
rate = 0.5

[[lines]]
name = "respect"
text = "And remember, respect is everything"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "must_hurt"
text = "Ouch, that had to hurt"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "get_some"
text = "Come get some"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "blow_ass"
text = "Blow it out your ass"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "bite_dust"
text = "Another one bites the dust"
female = true
pitch = -10.0
rate = 1.1

[[lines]]
name = "off_lawn"
text = "Get off my lawn"
female = true
pitch = -10.0
rate = 1.1

[[lines]]
name = "ass_grass"
text = "Your ass is grass, and I'm the lawnmower"
female = true
pitch = -10.0
rate = 1.1

[[lines]]
name = "eat_shit"
text = "Eat shit and die"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "get_wrecked"
text = "Get wrecked!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "you_suck"
text = "You guys suck!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "cake"
text = "Yeah, piece of cake!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "what_mess"
text = "Haaaaaaa, what a mess!"
female = true
pitch = -10.0
rate = 1.1

[[lines]]
name = "want_some"
text = "Who wants some?"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "piss_off"
text = "You're pissing me off!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "country_justice"
text = "Did someone order some good old country justice?"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "rip_em"
text = "Gonna rip 'em a new one!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "swallow_soul"
text = "I'll swallow your soul!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "boomstick"
text = "This... is my boomstick!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "hail_king"
text = "Hail to the king, baby."
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "shall_die"
text = "You shall die!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "groovy"
text = "Grewwwww veeeee!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "headshot"
text = "Boom! Headshot!"
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "intro_1"
text = "Ma'am, this is sheriff Buck."
female = false
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_2"
text = "I'm here to inform you that the bank has foreclosed on your ranch."
female = false
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_3"
text = "What in the hell?"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_4"
text = "My family has lived here for generations; it's my home!"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_5"
text = "I'm sorry, it's not your home anymore."
female = false
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_6"
text = "The hell it isn't!"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_7"
text = "You think you can come on to my property and take what is mine?"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_8"
text = "Yes, you have one day until we evict you by force."
female = false
pitch = -10.0
rate = 0.9

[[lines]]
name = "intro_9"
text = "I'd like to see you fucking try!"
female = true
pitch = -10.0
rate = 0.9

[[lines]]
name = "swat_gogogo"
text = "Go go go!"
female = false
city17 = true
pitch = -11.0
rate = 0.7

[[lines]]
name = "swat1"
text = "Target acquired"
female = false
city17 = true
pitch = -11.0
rate = 0.8

[[lines]]
name = "swat2"
text = "Lock an load"
female = false
city17 = true
pitch = -11.0
rate = 0.8

[[lines]]
name = "swat3"
text = "Enemy spotted"
female = false
city17 = true
pitch = -11.0
rate = 0.8

[[lines]]
name = "swat4"
text = "I need reinforcements"
female = false
city17 = true
pitch = -11.0
rate = 0.8

[[lines]]
name = "prepare0"
text = "Let's fortify this place in case they bring equipment."
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "prepare1"
text = "They play nasty. I better build more barricades."
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "prepare2"
text = "Those fuckers don't learn. More defenses."
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "prepare3"
text = "Screw those guys. Let's turn this place into a fortress."
female = true
pitch = -10.0
rate = 1.0

[[lines]]
name = "prepare4"
text = "Is that all you've got? I have a lot more crates!"
female = true
pitch = -10.0
rate = 1.0
